{"version":3,"file":"JupyterAuthError.js","sourceRoot":"","sources":["../../src/jupyter/JupyterAuthError.ts"],"names":[],"mappings":"AAAA;;;GAGG;AACH,MAAM,gBAAiB,SAAQ,KAAK;CAAG;AAEvC,eAAe,gBAAgB,CAAC"}